export const WorkData = [
  "Account Executive",
  "Account Manager",
  "Administrative Assistant",
  "Administrator",
  "Advisor",
  "Agent",
  "Aide",
  "Analyst",
  "Application Developer",
  "Architect",
  "Art Director",
  "Artist",
  "Assistant",
  "Assistant Professor",
  "Attendant",
  "Attorney",
  "Auditor",
  "Barista",
  "Bookkeeper",
  "Branch Manager",
  "Brand Strategist",
  "Broker",
  "Business Analyst",
  "Business Development Manager",
  "Business Manager",
  "Cashier",
  "Chief Architect",
  "Chief Engineer",
  "Chief Executive Officer (CEO)",
  "Chief Financial Officer (CFO)",
  "Chief Information Officer (CIO)",
  "Chief Information Security Officer (CISO)",
  "Chief Marketing Officer (CMO)",
  "Chief Operating Officer (COO)",
  "Chief People Officer (CPO)",
  "Chief Security Officer (CSO)",
  "Chief Technology Officer (CTO)",
  "Clerk",
  "Client Partner",
  "Controller",
  "Coordinator",
  "Counsel",
  "Creative Director",
  "Crew",
  "Curator",
  "Customer Advocate",
  "Customer Service Representative",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Designer",
  "Director",
  "Driver",
  "Economist",
  "Engineer",
  "Engineering Manager",
  "Entrepreneur",
  "Evangelist",
  "Executive Assistant",
  "Expert",
  "Founder",
  "General Counsel",
  "Generalist",
  "Graphic Designer",
  "Head of HR",
  "Head of Sales",
  "Human Resources Associate",
  "Human Resources Generalist",
  "Instructor",
  "Interaction Designer",
  "Intern",
  "Interpreter",
  "Journalist",
  "Leader / Lead / Team Lead",
  "Librarian",
  "Manager",
  "Managing Director",
  "Managing Partner",
  "Marketing Manager",
  "Media Buyer",
  "Media Producer",
  "Musician",
  "Office Manager",
  "Operations Analyst",
  "Operations Manager",
  "Operator",
  "Owner",
  "President",
  "Principal",
  "Producer",
  "Product Manager",
  "Product Owner",
  "Professor",
  "Program Manager",
  "Project Manager",
  "Proofreader",
  "Proprietor",
  "Receptionist",
  "Records Clerk",
  "Recruiter",
  "Research Manager",
  "Researcher",
  "Risk Manager",
  "Sales Associate",
  "Sales Engineer",
  "Sales Manager",
  "Sales Representative",
  "Sales Specialist",
  "Scientist / Research Scientist",
  "Security Engineer",
  "Software Architect",
  "Software Developer",
  "Software Engineer",
  "Solutions Architect",
  "Specialist",
  "Staff",
  "Store Manager",
  "Strategist",
  "Superintendent",
  "Supervisor",
  "Supply Manager",
  "Support Specialist",
  "Systems Developer",
  "Teacher",
  "Teaching Assistant",
  "Tech Lead",
  "Technician",
  "Test Engineer",
  "Trainee",
  "Trainer",
  "Translator",
  "Tutor",
  "UX Designer",
  "Videographer",
  "Waiter/Waitress",
  "Web Designer",
  "Web Developer",
  "Web Producer",
  "Worker",
  "Writer",
  "Account Executive",
  "Account Manager",
  "Administrative Assistant",
  "Administrator",
  "Advisor",
  "Agent",
  "Aide",
  "Analyst",
  "Application Developer",
  "Architect",
  "Art Director",
  "Artist",
  "Assistant",
  "Assistant Professor",
  "Attendant",
  "Attorney",
  "Auditor",
  "Barista",
  "Bookkeeper",
  "Branch Manager",
  "Brand Strategist",
  "Broker",
  "Business Analyst",
  "Business Development Manager",
  "Business Manager",
  "Cashier",
  "Chief Architect",
  "Chief Engineer",
  "Chief Executive Officer (CEO)",
  "Chief Financial Officer (CFO)",
  "Chief Information Officer (CIO)",
  "Chief Information Security Officer (CISO)",
  "Chief Marketing Officer (CMO)",
  "Chief Operating Officer (COO)",
  "Chief People Officer (CPO)",
  "Chief Security Officer (CSO)",
  "Chief Technology Officer (CTO)",
  "Clerk",
  "Client Partner",
  "Controller",
  "Coordinator",
  "Counsel",
  "Creative Director",
  "Crew",
  "Curator",
  "Customer Advocate",
  "Customer Service Representative",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Designer",
  "Director",
  "Driver",
  "Economist",
  "Engineer",
  "Engineering Manager",
  "Entrepreneur",
  "Evangelist",
  "Executive Assistant",
  "Expert",
  "Founder",
  "General Counsel",
  "Generalist",
  "Graphic Designer",
  "Head of HR",
  "Head of Sales",
  "Human Resources Associate",
  "Human Resources Generalist",
  "Instructor",
  "Interaction Designer",
  "Intern",
  "Interpreter",
  "Journalist",
  "Leader / Lead / Team Lead",
  "Librarian",
  "Manager",
  "Managing Director",
  "Managing Partner",
  "Marketing Manager",
  "Media Buyer",
  "Media Producer",
  "Musician",
  "Office Manager",
  "Operations Analyst",
  "Operations Manager",
  "Operator",
  "Owner",
  "President",
  "Principal",
  "Producer",
  "Product Manager",
  "Product Owner",
  "Professor",
  "Program Manager",
  "Project Manager",
  "Proofreader",
  "Proprietor",
  "Receptionist",
  "Records Clerk",
  "Recruiter",
  "Research Manager",
  "Researcher",
  "Risk Manager",
  "Sales Associate",
  "Sales Engineer",
  "Sales Manager",
  "Sales Representative",
  "Sales Specialist",
  "Scientist / Research Scientist",
  "Security Engineer",
  "Software Architect",
  "Software Developer",
  "Software Engineer",
  "Solutions Architect",
  "Specialist",
  "Staff",
  "Store Manager",
  "Strategist",
  "Superintendent",
  "Supervisor",
  "Supply Manager",
  "Support Specialist",
  "Systems Developer",
  "Teacher",
  "Teaching Assistant",
  "Tech Lead",
  "Technician",
  "Test Engineer",
  "Trainee",
  "Trainer",
  "Translator",
  "Tutor",
  "UX Designer",
  "Videographer",
  "Waiter/Waitress",
  "Web Designer",
  "Web Developer",
  "Web Producer",
  "Worker",
  "Writer",
];
